edge_config_data:
  saas:
    mgmt_url: https://api.enterprise.apigee.com
    branch:
      - develop:
          mvn_profile: test
          source_org: brahmajichittibonu-eval
          source_env: test
          target_org: brahmajichittibonu-eval
          target_env: prod
  hybrid:
